[package]
name = "provider"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
core-types.workspace = true
futures-util.workspace = true
genai.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
