[package]
name = "cloud-providers"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
syl-core.workspace = true
futures-util.workspace = true
genai.workspace = true
tools.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
ureq.workspace = true

[dev-dependencies]
memory.workspace = true
